name: 'Sysstat Action'
description: 'Collect system stats while running Github Actions workflows'
#inputs:
#  step:
#    description: 'Step to execute: one of launch, graph, cleanup'
#    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/post.js'
  
#    - name: "Upload graph as artifact"
#      if: inputs.step == 'graph'
#      uses: actions/upload-artifact@v4
#      with:
#        name: sar-report
#        path: build/sar-report/*
#        if-no-files-found: error
