name: 'Sysstat Action'
description: 'Collect system stats while running Github Actions workflows'
inputs:
  github_token:
    description: "GitHub Access Token"
    default: ${{ github.token }}
    required: false
  report_artifact_name:
    description: "Name of the artifact that should be attached to the workflow"
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/post.js'
  
#    - name: "Upload graph as artifact"
#      if: inputs.step == 'graph'
#      uses: actions/upload-artifact@v4
#      with:
#        name: sar-report
#        path: build/sar-report/*
#        if-no-files-found: error
